### ISSUE TITLE
comparison with rogpeppe/go-internal ?

### ISSUE THREAD

**Issue by marco-m-pix4d** [ancientlore/gscript#1]
Hello @ancientlore,

I am an happy user of rogpeppe/go-internal/testscript, which you probably know as a previous version of the same extracted code from Go internal.

I tried once to use rsc.io/script but I have to say it was not evident at all (no examples, except the ones directly in go src) and I gave up.

I was wondering what is your opinion ? Thanks!

**Comment by ancientlore** [comment]
Hi Marco,

I first learned about `rsc.io/script` from [this thread](https://groups.google.com/g/golang-nuts/c/leGd1uOXpIA/m/JtzYCrKBAQAJ) on golang-nuts. My use case was outside of testing - basically I was looking for a very simple, embeddable scripting system to use in other projects. The needs were pretty basic. I have not looked deeply at `rogpeppe/go-internal/testscript` yet.

I found the documentation a bit lacking and it took some time to figure out how to add additional commands and conditions. In particular I was trying to add conditional logic. You can add conditions that look for one thing, like "an environment variable is set". But it doesn't seem flexible enough to test that an environment variable has a particular value before executing a command. I suppose you could implement a command that has options for that. But as I said, I had a different use case in mind.

If you are happy with `rogpeppe/go-internal/testscript`, there is probably no real reason to switch.

Best,

Mike

**Comment by marco-m-pix4d** [comment]
Thanks for the answer Michael!
